# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 18:11
from __future__ import unicode_literals

import app.services.utils
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('x_coord', models.CharField(default='', max_length=256)),
                ('y_coord', models.CharField(default='', max_length=256)),
                ('property_index', models.IntegerField(default=0)),
                ('publicized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicized', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('title', models.CharField(default='', max_length=256)),
                ('raw_data_file', models.FileField(default='', upload_to=app.services.utils.user_upload_dir)),
                ('analyzed_json_filename', models.CharField(default='', max_length=256)),
                ('anomaly_json_filename', models.CharField(default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromNode', models.IntegerField(db_index=True, default=0)),
                ('toNode', models.IntegerField(db_index=True, default=0)),
                ('weight', models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.CharField(db_index=True,default=0, max_length=30)),
                ('degree', models.CharField(db_index=True, default=0, max_length=30)),
                ('count', models.CharField(db_index=True, default=0, max_length=30)),
                ('pagerank', models.FloatField(db_index=True, default=0)),
                ('pagerank_t', models.FloatField(db_index=True, default=0)),
                ('pagerank_t_count', models.FloatField(db_index=True, default=0)),
                ('v_1', models.FloatField(db_index=True, default=0)),
                ('v_2', models.FloatField(db_index=True, default=0)),
                ('v_3', models.FloatField(db_index=True, default=0)),
                ('v_4', models.FloatField(db_index=True, default=0)),
                ('v_5', models.FloatField(db_index=True, default=0)),
                ('v_6', models.FloatField(db_index=True, default=0)),
                ('v_7', models.FloatField(db_index=True, default=0)),
                ('v_8', models.FloatField(db_index=True, default=0)),
                ('v_9', models.FloatField(db_index=True, default=0)),
                ('v_10', models.FloatField(db_index=True, default=0)),
                ('v_1_t', models.FloatField(db_index=True, default=0)),
                ('v_2_t', models.FloatField(db_index=True, default=0)),
                ('v_3_t', models.FloatField(db_index=True, default=0)),
                ('v_4_t', models.FloatField(db_index=True, default=0)),
                ('v_5_t', models.FloatField(db_index=True, default=0)),
                ('v_6_t', models.FloatField(db_index=True, default=0)),
                ('v_7_t', models.FloatField(db_index=True, default=0)),
                ('v_8_t', models.FloatField(db_index=True, default=0)),
                ('v_9_t', models.FloatField(db_index=True, default=0)),
                ('v_10_t', models.FloatField(db_index=True, default=0)),
                ('dataset', models.ForeignKey(default = 1, on_delete=django.db.models.deletion.CASCADE, to='app.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dataset'),
        ),
    ]
