# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170405_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='raw_data',
            new_name='raw_data_file',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmark',
            name='publicized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='anomaly_json_filename',
            field=models.CharField(default='', max_length=256),
        ),
    ]
