# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170408_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='dataset',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='app.Dataset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmark',
            name='property_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='x_coord',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='y_coord',
            field=models.CharField(default='', max_length=256),
        ),
    ]
