# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170615_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='analyzed_json_filename',
            new_name='analyzed_filepath',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='anomaly_json_filename',
            new_name='anomaly_filepath',
        ),
    ]
