# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170615_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
