# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170519_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='v_10_t',
        ),
    ]
