# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_node_v_10_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='v_10_t',
            field=models.CharField(db_index=True, default=0, max_length=30),
        ),
    ]
