# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170616_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='clustering_coefficient',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
