# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_node_dataset'),
        ('app', '0007_node_clustering_coefficient'),
    ]

    operations = [
    ]
