# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_node_v_10_t'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
