# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 04:06
from __future__ import unicode_literals

import app.services.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20170617_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='analyzed_filepath',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='anomaly_filepath',
        ),
        migrations.AddField(
            model_name='dataset',
            name='analyzed_fulldata_file',
            field=models.FileField(default='', upload_to=app.services.utils.user_processed_dir),
        ),
        migrations.AddField(
            model_name='dataset',
            name='analyzed_graph_file',
            field=models.FileField(default='', upload_to=app.services.utils.user_processed_dir),
        ),
        migrations.AddField(
            model_name='dataset',
            name='anomaly_scores_file',
            field=models.FileField(default='', upload_to=app.services.utils.user_processed_dir),
        ),
    ]
