# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170519_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromNode', models.IntegerField(db_index=True, default=0)),
                ('toNode', models.IntegerField(db_index=True, default=0)),
                ('weight', models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('nodeid', models.CharField(default=0, max_length=30, primary_key=True, serialize=False)),
                ('degree', models.CharField(db_index=True, default=0, max_length=30)),
                ('count', models.CharField(db_index=True, default=0, max_length=30)),
                ('pagerank', models.CharField(db_index=True, default=0, max_length=30)),
                ('pagerank_t', models.CharField(db_index=True, default=0, max_length=30)),
                ('pagerank_t_count', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_1', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_2', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_3', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_4', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_5', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_6', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_7', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_8', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_9', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_10', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_1_t', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_2_t', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_3_t', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_4_t', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_5_t', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_6_t', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_7_t', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_8_t', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_9_t', models.CharField(db_index=True, default=0, max_length=30)),
                ('v_10_t', models.CharField(db_index=True, default=0, max_length=30)),
            ],
        ),
    ]
