# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_edge_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='anomaly_scores_file',
        ),
        migrations.AddField(
            model_name='dataset',
            name='combined_scores_files',
            field=models.CharField(default='', max_length=512),
        ),
    ]
