# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170623_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='property_index',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='prop',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
