# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-30 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170904_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='node_id',
            field=models.IntegerField(default=269),
            preserve_default=False,
        ),
    ]
