# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_edge_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='pagerank',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='pagerank_t',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='pagerank_t_count',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_1',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_10',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_10_t',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_1_t',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_2',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_2_t',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_3',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_3_t',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_4',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_4_t',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_5',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_5_t',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_6',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_6_t',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_7',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_7_t',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_8',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_8_t',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_9',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='v_9_t',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
