# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-30 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_dataset_trashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='note',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
